### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by woodardj** [rrodrigonuez/WP-Block-Referrer-Spam#1]
Looks like there's some sort of issue with the WP version requirement, and I'm curious if PHP 5.3 is actually required:

```
WP Block Referrer Spam error: Your environment doesn't meet all of the system requirements listed below.
* PHP 5.3+ (You're running version 5.2.17)
* WordPress 3.1+ (You're running version 4.2.3)
```

**Comment by rrodrigonuez** [comment]
Thanks for your comment. 

There is no problem with your WordPress version, the problem that you are having is related to your PHP version which is lower than the one required (5.3).
I haven't test it on PHP 5.2, but if you want you can remove or comment the requirements checking and see if it works on your site.
But I bet you that some of the PHP methods that this plugin uses are only available on PHP 5.3 and above. 

Thanks again!

**Comment by woodardj** [comment]
Excellent — I upgraded PHP and all is well. My main worry was that there was some kind of issue checking the version number on the WP side. But I guess that weird messaging is probably a WP core issue. Thanks for replying!

**Comment by rrodrigonuez** [comment]
I am glad the issue was fixed!

Again, there is no problem with your WP version, read the message again:
WP Block Referrer Spam error: Your environment **doesn't meet all** of the system requirements listed below.

And then it lists the requirements for this plugin:
- PHP 5.3+ (You're running version 5.2.17)
- WordPress 3.1+ (You're running version 4.2.3)

That means that the only requirement that your environment doesn't meet is the PHP version which was lower than required. WP version was just fine.

Thanks!
